### ISSUE TITLE
Unable to open kdbx database with keyfile

### ISSUE THREAD

**Issue by Grimms** [loomanw/robotframework-keepasslibrary#14] opened 2022-03-11 11:40 UTC
Hi!
I was looking for a way to securely manage passwords in my Robot/Selenium test suite, and your keepasslibrary looks like just the ticket.

Unfortunately I can't seem to open my kdbx database with keepasslibrary using the keyfile. Opening the database works when I use a password, but not when I try using a keyfile, or a combination of password and keyfile. Manually opening the database with the keyfile works fine, but something's preventing keepasslibrary from succeeding.

All the information about the error I'm getting is the message "CredentialsError", which I suspect originates from pykeepass (https://github.com/libkeepass/pykeepass/search?q=CredentialsError) and gets patched through as is. Maybe it's about compatibility between current keepasslibrary and pykeepass versions?

I'm on Windows 10, for what it's worth.

![credentialsError_01](https://user-images.githubusercontent.com/6837492/157858103-79a58cac-25aa-4091-afcd-57bce10d2db6.PNG)

**Comment by loomanw** [comment] 2022-08-03 14:12
Hi,

The method you want to use is part of the regression test:
https://app.travis-ci.com/github/loomanw/robotframework-keepasslibrary/builds/246791499


Located in:
Composite Master Key.robot
[https://github.com/loomanw/robotframework-keepasslibrary/blob/master/atests/Composite%20Master%20Key.robot](url)
All regression test and data files
https://github.com/loomanw/robotframework-keepasslibrary/tree/master/atests

Please download and verify that "Composite Master Key.robot" succeeds on your system.

The dependacy to PyKeePass is fixed ( 3.2.1 ), currently working on upgrading to 4.x

Regards William

**Comment by pluypen** [comment] 2022-11-11 06:47
I've had the same issue. In my case it was caused by using a 2.0 format keyfile (current default format in Keepass). This new keyfile format is however not supported by pykeepass V3.2.2.  It will be supported by pykeepass V4.0.1 and up.

When I made a new keyfile using 1.0 format  (this is an option in Keepass) all worked fine again.

**Comment by sedzrok** [comment] 2023-06-09 11:01
Hello,
I have the same issue "CredentialsError" when using keyfile format version 2.0
Someone know when this issue will be fixed?

Regards.

**Comment by loomanw** [comment] 2023-07-18 17:46
v0.4.0 is available with pykeepass v4.x, enabling keyfile format 2 support
https://pypi.org/project/robotframework-keepasslibrary/

**Comment by sedzrok** [comment] 2023-07-28 15:07
Thanks for the new version of robotframework-keepasslibrary.
keyfile format 2 is working as expected with new version 0.4.0

**Closed as completed** 2023-09-01 15:20 UTC
